# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/sensor_data.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsrc/proto/sensor_data.proto\"\xe7\x01\n\rSensorReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12 \n\x0bsensor_type\x18\x03 \x01(\x0e\x32\x0b.DeviceType\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12.\n\x08metadata\x18\x07 \x03(\x0b\x32\x1c.SensorReading.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"?\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\";\n\x13GatewayAnnouncement\x12\x12\n\ngateway_ip\x18\x01 \x01(\t\x12\x10\n\x08udp_port\x18\x02 \x01(\r\"F\n\rDeviceCommand\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03*a\n\nDeviceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bTEMPERATURE\x10\x01\x12\x0c\n\x08HUMIDITY\x10\x02\x12\t\n\x05\x41LARM\x10\x03\x12\r\n\tLAMP_POST\x10\x04\x12\r\n\tSEMAPHORE\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.sensor_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENSORREADING_METADATAENTRY']._options = None
  _globals['_SENSORREADING_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DEVICETYPE']._serialized_start=463
  _globals['_DEVICETYPE']._serialized_end=560
  _globals['_SENSORREADING']._serialized_start=32
  _globals['_SENSORREADING']._serialized_end=263
  _globals['_SENSORREADING_METADATAENTRY']._serialized_start=216
  _globals['_SENSORREADING_METADATAENTRY']._serialized_end=263
  _globals['_RESPONSE']._serialized_start=265
  _globals['_RESPONSE']._serialized_end=328
  _globals['_GATEWAYANNOUNCEMENT']._serialized_start=330
  _globals['_GATEWAYANNOUNCEMENT']._serialized_end=389
  _globals['_DEVICECOMMAND']._serialized_start=391
  _globals['_DEVICECOMMAND']._serialized_end=461
# @@protoc_insertion_point(module_scope)
