# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import sensor_data_pb2 as proto_dot_sensor__data__pb2


class DeviceControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommand = channel.unary_unary(
                '/DeviceControl/SendCommand',
                request_serializer=proto_dot_sensor__data__pb2.CommandRequest.SerializeToString,
                response_deserializer=proto_dot_sensor__data__pb2.CommandResponse.FromString,
                )
        self.SendTcpData = channel.unary_unary(
                '/DeviceControl/SendTcpData',
                request_serializer=proto_dot_sensor__data__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_sensor__data__pb2.CommandResponse.FromString,
                )
        self.SetSemaphoreLight = channel.unary_unary(
                '/DeviceControl/SetSemaphoreLight',
                request_serializer=proto_dot_sensor__data__pb2.SemaphoreLightStateRequest.SerializeToString,
                response_deserializer=proto_dot_sensor__data__pb2.CommandResponse.FromString,
                )


class DeviceControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTcpData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSemaphoreLight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=proto_dot_sensor__data__pb2.CommandRequest.FromString,
                    response_serializer=proto_dot_sensor__data__pb2.CommandResponse.SerializeToString,
            ),
            'SendTcpData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTcpData,
                    request_deserializer=proto_dot_sensor__data__pb2.Empty.FromString,
                    response_serializer=proto_dot_sensor__data__pb2.CommandResponse.SerializeToString,
            ),
            'SetSemaphoreLight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSemaphoreLight,
                    request_deserializer=proto_dot_sensor__data__pb2.SemaphoreLightStateRequest.FromString,
                    response_serializer=proto_dot_sensor__data__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceControl/SendCommand',
            proto_dot_sensor__data__pb2.CommandRequest.SerializeToString,
            proto_dot_sensor__data__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendTcpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceControl/SendTcpData',
            proto_dot_sensor__data__pb2.Empty.SerializeToString,
            proto_dot_sensor__data__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSemaphoreLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceControl/SetSemaphoreLight',
            proto_dot_sensor__data__pb2.SemaphoreLightStateRequest.SerializeToString,
            proto_dot_sensor__data__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
